In [1]:
import matplotlib as mpl
import numpy as np
import torch

In [12]:
torch.backends.mps.is_available()

True

In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(f'x_data:\n{x_data}')

x_data:
tensor([[1, 2],
        [3, 4]])


In [6]:
shape = (3,5,)
rand_tensor = torch.rand(shape)
print(f'rand_tensor:\n{rand_tensor}')

rand_tensor:
tensor([[0.3394, 0.6642, 0.6843, 0.6609, 0.1114],
        [0.2988, 0.0558, 0.8576, 0.8454, 0.8640],
        [0.5995, 0.1245, 0.4464, 0.9988, 0.7878]])


In [11]:
tensor = torch.rand(3,4).to("mps")
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.1560, 0.0469, 0.1083, 0.5984],
        [0.7459, 0.2227, 0.0726, 0.9140],
        [0.6869, 0.7567, 0.3341, 0.1257]], device='mps:0')
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: mps:0


In [31]:
tensor = torch.rand(2, 2, 3).to('mps')
print(tensor)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])

tensor([[[0.6997, 0.0509, 0.8610],
         [0.0058, 0.5736, 0.9979]],

        [[0.2945, 0.6183, 0.1722],
         [0.3662, 0.4476, 0.2519]]], device='mps:0')
First row:  tensor([[0.6997, 0.0509, 0.8610],
        [0.0058, 0.5736, 0.9979]], device='mps:0')
First column:  tensor([[0.6997, 0.0509, 0.8610],
        [0.2945, 0.6183, 0.1722]], device='mps:0')
Last column: tensor([[0.8610, 0.9979],
        [0.1722, 0.2519]], device='mps:0')


In [32]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[[0.6997, 0.0509, 0.8610],
         [0.0058, 0.5736, 0.9979],
         [0.6997, 0.0509, 0.8610],
         [0.0058, 0.5736, 0.9979],
         [0.6997, 0.0509, 0.8610],
         [0.0058, 0.5736, 0.9979]],

        [[0.2945, 0.6183, 0.1722],
         [0.3662, 0.4476, 0.2519],
         [0.2945, 0.6183, 0.1722],
         [0.3662, 0.4476, 0.2519],
         [0.2945, 0.6183, 0.1722],
         [0.3662, 0.4476, 0.2519]]], device='mps:0')


In [33]:
t2 = torch.cat([tensor, tensor, tensor], dim=2)
print(t2)

tensor([[[0.6997, 0.0509, 0.8610, 0.6997, 0.0509, 0.8610, 0.6997, 0.0509,
          0.8610],
         [0.0058, 0.5736, 0.9979, 0.0058, 0.5736, 0.9979, 0.0058, 0.5736,
          0.9979]],

        [[0.2945, 0.6183, 0.1722, 0.2945, 0.6183, 0.1722, 0.2945, 0.6183,
          0.1722],
         [0.3662, 0.4476, 0.2519, 0.3662, 0.4476, 0.2519, 0.3662, 0.4476,
          0.2519]]], device='mps:0')


In [42]:
tensor = torch.rand(2, 2).to('mps')
print(tensor)
print(tensor.T)

tensor([[0.2070, 0.8740],
        [0.1247, 0.7902]], device='mps:0')
tensor([[0.2070, 0.1247],
        [0.8740, 0.7902]], device='mps:0')


In [43]:
y1 = tensor @ tensor.T
print(y1)

tensor([[0.8067, 0.7164],
        [0.7164, 0.6400]], device='mps:0')


In [44]:
z1 = tensor * tensor
print(z1)

tensor([[0.0429, 0.7638],
        [0.0156, 0.6245]], device='mps:0')
